name: "Hello world workflow"

on:
    push:
        branches:
            - master
            - production
jobs:
    hello_world:
        runs-on: ubuntu-latest # Runners can either be provision via GitHub or by cloud platforms
        steps:
            - name: "Print hello world"
              run: echo "Hello world" 
