name: "Push changes to master workflow"
# Triggers an "on" event when we push code to master
on:
  push:
    branches:
      - master
jobs:
  pushed_to_master:
    runs-on: ubuntu-latest
    steps:
      - name: "Code pushed to master"
        run: echo "Code has been pushed to master"